services:
  rex:
    container_name: rex
    build:
      dockerfile: dockerfile
      context: https://github.com/guesswho1234/Rex.git#main
    restart: unless-stopped
    ports:
      - "32780:3838"
    volumes:
      - type: bind
        source: /home/rex.sqlite
        target: /rex/rex.sqlite
      - shared-content:/tmp/
  rex-worker:
    container_name: rex-worker
    build:
      dockerfile: dockerfile_worker
      context: https://github.com/guesswho1234/Rex.git#main
    restart: unless-stopped
    volumes:
      - shared-content:/tmp/

volumes:
  shared-content:
      