version: "3.8"

services:
  rex:
    container_name: rex
    build:
      dockerfile: dockerfile
      args:
        UID: 1001
        GID: 1001
      context: https://github.com/guesswho1234/Rex.git#main
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    user: rexuser
    restart: unless-stopped
    ports:
      - "32780:3838"
    volumes:
      - type: bind
        source: /home/rex.sqlite
        target: /rex/rex.sqlite
      - shared-content:/tmp/
    # mem_limit: 512m        # Max memory
    # mem_reservation: 256m  # Soft limit
    # cpus: 0.5              # Max 50% of one CPU core
  rex-worker:
    container_name: rex-worker
    build:
      dockerfile: dockerfile_worker
      args:
        UID: 1001
        GID: 1001
      context: https://github.com/guesswho1234/Rex.git#main
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    restart: unless-stopped
    user: rexuser
    volumes:
      - shared-content:/tmp/
    # mem_limit: 512m        # Max memory
    # mem_reservation: 256m  # Soft limit
    # cpus: 0.5              # Max 50% of one CPU core

volumes:
  shared-content:
      