---
title: "Exam Report"
output:
  pdf_document:
    fig_caption: yes
    keep_tex: true
    latex_engine: xelatex
    fig_crop: FALSE
mainfont: "TeX Gyre Heros"
params:
  validExams: NULL
  exerciseShortNames: NULL
  exerciseNames: NULL
  plots: NULL
  captions: NULL
  descriptions: NULL
  mark: NULL
  markLabels: NULL
  markTable: NULL
  points: NULL
  numExercises: NULL
  examMaxPoints: NULL
  exercisePoints: NULL
  ir_binary: NULL
  ir_ok: NULL
  hm: NULL
  rasch_model: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.align = 'center')
```

```{r first-page-table, echo=FALSE, results='asis'}
cat("### Table 1: Exam Overview\n\n")

exam_table = data.frame(
  description = "Number of valid exams",
  number = params$validExams[1],
  stringsAsFactors = FALSE
)

colnames(exam_table) <- c("", "")

knitr::kable(
  exam_table,
  format = "pandoc",
  booktabs = TRUE,
  align = "ll"
)

cat("### Table 2: Exercise Overview\n\n")

exercise_table = data.frame(
  Id = params$exerciseShortNames,
  Name = params$exerciseNames,
  stringsAsFactors = FALSE
)

knitr::kable(
  exercise_table,
  format = "pandoc",
  booktabs = TRUE,
  align = "ll"
)
```

```{r plot-loop, results='asis', echo=FALSE, fig.width=8, fig.height=9, fig.pos='H', dpi=300, family='Helvetica'}
for (i in seq_along(params$plots)) {
  cat(sprintf("### Figure %d: %s\n\n", i, params$captions[[i]]))

  invisible(eval(params$plots[[i]]))
  cat("\n\n", params$descriptions[[i]], "\n\n")
}
```
